language: r

sudo: required
cache: packages
warnings_are_errors: true

apt_packages:
  - libmagick++-dev

r:
  - release
  - devel
  
notifications:
    email:
    on_success: change
    on_failure: change
